export const SEO_CONFIG = {
    default: {
        title: "Nigsoft Private Limited | Healthcare Management Software",
        description: "We create robust healthcare software for medical laboratories, pharmacies, clinics, and hospitals to provide their service very efficiently. Book a free DEMO.",
        keywords: "NIG Software solutions, NIGSOFT Pvt Ltd, free demo, healthcare software, medical management system, hospital software India, pharmacy management tools, lab information system",
        canonical: "https://www.nigsoft.com/",
    },
    home: {
        title: "NIGSOFT Pvt Ltd | Healthcare management software.",
        description: "We create robust healthcare software for medical laboratories, pharmacies, clinics, and hospitals to provide their service very efficiently. Book a free DEMO.",
        keywords: "NIG Software solutions, NIGSOFT Pvt Ltd, free demo, healthcare software, digital healthcare solutions, medical software salem, hospital automation, clinic management",
        canonical: "https://www.nigsoft.com/",
    },
    about: {
        title: "We are a leading healthcare software company. | Nigsoft",
        description: "Managing Hospitals, clinics, or labs can be a highly challenging job, so to make those things easier we deliver an outstanding technological experience to you.",
        keywords: "NIG Software solutions, free demo software, healthcare software in India, healthcare technology partner, medical software company, healthcare innovation salem",
        canonical: "https://www.nigsoft.com/about",
    },
    lab: {
        title: "Lab Management Software | Nigsoft",
        description: "This software reduces all your hard work and provides you a smart working atmosphere to make your business effective and efficient.",
        keywords: "Medical lab software, Free demo, Medical lab software in India, Pathological lab management, LIMS software India, blood test reporting software, laboratory automation",
        canonical: "https://www.nigsoft.com/product/labmanagementsoftware",
    },
    pharmacy: {
        title: "Pharmacy Billing & Management Software | Nigsoft",
        description: "This software will manage your stock, indicates you whenever a stock management issue arises, and many more features.",
        keywords: "Pharmacy management software, Pharmacy billing software, Free demo, chemist shop software, pharmacy inventory management, medical store billing system, drug inventory software",
        canonical: "https://www.nigsoft.com/product/pharmacymanagementsoftware",
    },
    hospital: {
        title: "Hospital & Clinic Management Software | Nigsoft",
        description: "This tool is particularly designed for hospitals and doctors who own a clinic, this will help you to maintain your hospital by providing a digital environment with futuristic technologies.",
        keywords: "Hospital management software, Clinic management software, Free demo, HMS software India, EMR systems, patient record management, clinic automation tools",
        canonical: "https://www.nigsoft.com/product/hospitalerpsoftware",
    },
    dental: {
        title: "Dental Management Software | Nigsoft",
        description: "Smart dental management software to simplify clinic operations. Manage appointments, patient records, and billing with ease.",
        keywords: "Dental management software, Dental clinic software, Free demo, dentist practice management, dental EMR, dental clinic billing, tooth chart software",
        canonical: "https://www.nigsoft.com/product/dentalclinicsoftware",
    },
    hr: {
        title: "HR Management Software | Nigsoft",
        description: "A powerful HR management platform designed to streamline employee operations, automate payroll, ensure compliance, and improve workforce productivity.",
        keywords: "HR management software, Payroll software, Workforce management, employee management system, HRMS India, payroll automation, attendance tracking software",
        canonical: "https://www.nigsoft.com/product/hrmssoftware",
    },
    contact: {
        title: "Nigsoft Customer Service | Contact Nigsoft",
        description: "We always put the Customer as Our Priority so our doors are always open for everyone to have a chat with us.",
        keywords: "Software company in Salem, healthcare software companies, contact nigsoft, healthcare tech support, software inquiry, product demo request",
        canonical: "https://www.nigsoft.com/contact",
    },
    partner: {
        title: "Become a Partner | Grow Your Business with Nigsoft",
        description: "Join our elite partner network and deliver future-proof healthcare management solutions. Get exclusive access to enterprise resources and benefits.",
        keywords: "healthcare software partnership, business partnership, nigsoft partner, reseller program, medical software distributor, healthcare affiliate program",
        canonical: "https://www.nigsoft.com/partner",
    },
    career: {
        title: "Join Our Team | Careers at Nigsoft",
        description: "Explore career opportunities at Nigsoft. We are always looking for passionate individuals to help us build the future of healthcare technology.",
        keywords: "careers at nigsoft, software jobs Salem, healthcare tech jobs, web developer jobs, sales jobs salem, medical software careers",
        canonical: "https://www.nigsoft.com/career",
    },
    bills: {
        title: "Nigbills.com | Smart Billing Solutions | Nigsoft",
        description: "To get a desirable profit, Do smart business with Nigbills software. Automated billing and invoicing for modern businesses.",
        keywords: "billing software, invoicing tool, Nigbills, pharmacy billing, retail billing software, GST billing system, invoice generator India",
        canonical: "https://www.nigsoft.com/product/billinginvoicesoftware",
    },
    bloodbank: {
        title: "Blood Bank Management Software | Nigsoft",
        description: "Efficiently manage blood donor records, stock, and distribution with our robust blood bank management system.",
        keywords: "blood bank software, donor management, healthcare software, blood inventory management, transfusion service software, blood donation tracking",
        canonical: "https://www.nigsoft.com/product/bloodbankmanagementsoftware",
    },
    gellplus: {
        title: "Gell+ Mobile App | Smart Healthcare in Your Pocket | Nigsoft",
        description: "Experience the next level of healthcare management with the Gell+ mobile app. Access patient records and manage your clinic on the go.",
        keywords: "healthcare app, mobile clinic management, Gell+, Nigsoft app, patient engagement app, mobile EMR reader, digital healthcare app",
        canonical: "https://www.nigsoft.com/product/mobileappforpatients",
    },
    bpo: {
        title: "Business Process Outsourcing (BPO) Services | Nigsoft",
        description: "We provide IT-enabled BPO services all across India. Focus on your core business while we handle your operational excellence.",
        keywords: "BPO services, ITES, outsourcing India, Nigsoft BPO, business process management, data entry services, customer support outsourcing",
        canonical: "https://www.nigsoft.com/services/bpo",
    },
    ecommerce: {
        title: "E-commerce Website Development | Growth-Focused Online Stores",
        description: "We provide high-level e-commerce solutions to promote your business online. Custom designs that convert visitors into customers.",
        keywords: "ecommerce development, online store builder, custom ecommerce, Nigsoft, Shopify experts salem, WooCommerce development, digital commerce solutions",
        canonical: "https://www.nigsoft.com/services/ecommerce-development",
    },
    project_development: {
        title: "Custom Project Development | Tailored IT Solutions | Nigsoft",
        description: "Leading IT company in Salem developing custom products and projects based on client needs. We invent the future together.",
        keywords: "custom software development, project development, MVP development, software engineering salem, enterprise software solutions, agile development",
        canonical: "https://www.nigsoft.com/services/project-development",
    },
    corporate_website: {
        title: "Corporate Website Development | Professional Online Presence",
        description: "A successful website attracts the right visitors and leads. Build a strong corporate profile with Nigsoft's expert web team.",
        keywords: "corporate web design, business website, professional web development, corporate digital identity, startup website design, premium web services",
        canonical: "https://www.nigsoft.com/services/corporate-website",
    },
    cms: {
        title: "CMS Website Development | Content Management Systems | Nigsoft",
        description: "Great content is the best sales tool. We build robust CMS websites (WordPress, Joomla, etc.) for easy content management.",
        keywords: "CMS development, WordPress website, content management system, Headless CMS, Drupal development, Joomla services",
        canonical: "https://www.nigsoft.com/services/cms-development",
    },
    maintenance: {
        title: "Website Maintenance & Support | Keep Your Site Running 24/7",
        description: "Your website promotes you 24/7. Keep it updated and high-performing with our comprehensive maintenance services.",
        keywords: "website maintenance, technical support, web updates, Nigsoft, website security audits, speed optimization, monthly web support",
        canonical: "https://www.nigsoft.com/services/website-maintenance",
    },
    ui_ux: {
        title: "UI/UX Design & Development | User-Centric Experiences | Nigsoft",
        description: "Design is not just what it looks like, it's how it works. We create intuitive UI/UX for better user engagement.",
        keywords: "UI/UX design, user experience, web design agency, Nigsoft, prototyping, wireframing, user interface design India, responsive UI",
        canonical: "https://www.nigsoft.com/services/ui-ux-development",
    },
    designing: {
        title: "Creative Graphic Designing | Postcard & Social Media Design",
        description: "Extreme-quality content and design for social media posters, postcards, and branding. Changing the world one click at a time.",
        keywords: "graphic design, social media posters, postcard design, branding, logo design salem, marketing materials, brand identity design",
        canonical: "https://www.nigsoft.com/services/designing",
    },
    seo_smm: {
        title: "SEO & Social Media Marketing (SMM) | Build Your Online Reputation",
        description: "SEO is an investment for future growth. Build digital relationships and reputation before closing a sale with our marketing experts.",
        keywords: "SEO services, SMM, digital marketing India, search engine optimization, pay per click, social media growth, online presence management",
        canonical: "https://www.nigsoft.com/services/seo-smm",
    },
    it_services: {
        title: "IT-Enabled Services | Unbreakable Success for Your Business",
        description: "We provide IT-enabled services across India. Whatever the situation, our support team is always there to guide you.",
        keywords: "IT services, healthcare tech support, service provider India",
        canonical: "https://www.nigsoft.com/services",
    },
    privacy: {
        title: "Privacy Policy | Nigsoft Private Limited",
        description: "Learn how we protect your personal data and the steps we take to keep your information safe and secure.",
        keywords: "privacy policy, data protection, security, Nigsoft",
        canonical: "https://www.nigsoft.com/privacypolicy",
    },
    terms: {
        title: "Terms of Use | Nigsoft Private Limited",
        description: "Understand our service obligations and user requirements for continued use of Nigsoft's healthcare solutions.",
        keywords: "terms of service, legal, user agreement, Nigsoft",
        canonical: "https://www.nigsoft.com/termsofservice",
    },
    demo: {
        title: "Book a Free Demo | Experience Nigsoft Healthcare Tech",
        description: "Have a glimpse of our software with complete training and support. Book your personalized demo right away.",
        keywords: "free demo, software trial, healthcare tech demo",
        canonical: "https://www.nigsoft.com/book-demo",
    },
    tech_react: {
        title: "React Native Development | Mobile App Expertise",
        description: "Building high-performance mobile applications with React Native. Scalable and efficient cross-platform solutions.",
        keywords: "React Native, mobile app development, cross-platform apps",
        canonical: "https://www.nigsoft.com/services/mobile-development",
    },
    web_development: {
        title: "Custom Web Development Services | Modern & Scalable Websites",
        description: "Transform your digital presence with custom web solutions. We create responsive, fast, and user-friendly websites that drive business growth.",
        keywords: "web development, custom website, responsive design, Nigsoft, Next.js developers, Fullstack development, modern web technologies",
        canonical: "https://www.nigsoft.com/services/web-development",
    },
    saas_development: {
        title: "SaaS Development Services | Scalable Cloud Solutions | Nigsoft",
        description: "Build robust, scalable, and secure SaaS applications with our expert development team. Turn your idea into a thriving cloud product.",
        keywords: "SaaS development, cloud software, multi-tenant apps, Nigsoft, SaaS architecture, cloud application development, software as a service company",
        canonical: "https://www.nigsoft.com/services/saas-development",
    },
    ai_integration: {
        title: "AI Integration Services | Smart Business Automation | Nigsoft",
        description: "Leverage the power of Artificial Intelligence to automate workflows and gain insights. Custom AI solutions for modern enterprises.",
        keywords: "AI integration, machine learning, business automation, Nigsoft AI, Large Language Models, AI chatbots, predictive intelligence",
        canonical: "https://www.nigsoft.com/services/ai-integration",
    },
    disclaimer: {
        title: "Disclaimer | Nigsoft Private Limited",
        description: "Legal disclaimer regarding the information provided on our website and the use of our healthcare software solutions.",
        keywords: "disclaimer, legal info, healthcare software disclaimer",
        canonical: "https://www.nigsoft.com/disclaimer",
    },
    schedule_call: {
        title: "Schedule a Strategic Consultation | Priority Access | Nigsoft",
        description: "Join a dedicated session with our solutions architects to map out your digital growth strategy and unlock operational excellence.",
        keywords: "schedule call, consultation, business strategy, healthcare tech advisor",
        canonical: "https://www.nigsoft.com/schedule-call",
    },
    hims_certification: {
        title: "HIMS Certification | AI-Enabled Healthcare Professional Training | Nigsoft",
        description: "Master Hospital Information Management Systems in 30 days. Join the next generation of AI-enabled doctors and healthcare professionals. Live training, practical tasks, career transformation.",
        keywords: "HIMS certification, hospital management training, healthcare IT course, medical software training, AI healthcare, MBBS internship, doctor training program, hospital information system, healthcare technology certification",
        canonical: "https://www.nigsoft.com/hims-certification",
    },
    hims_apply: {
        title: "Apply for HIMS Certification | Secure Your Spot | Nigsoft Academy",
        description: "Apply now for the Nigsoft HIMS Certification program. Limited seats available. 30-day intensive training for healthcare professionals. Next batch starting soon.",
        keywords: "HIMS application, healthcare training enrollment, medical IT course admission, hospital management certification apply, doctor training program, healthcare professional course",
        canonical: "https://www.nigsoft.com/hims-apply",
    },
};
